package mimir

const (
	countryCodeSize = 2

	ad = countryCode("AD") // Andorra
	ae = countryCode("AE") // United Arab Emirates
	al = countryCode("AL") // Albania
	at = countryCode("AT") // Austria
	az = countryCode("AZ") // Azerbaijan
	ba = countryCode("BA") // BA – Bosnia and Herzegovina
	be = countryCode("BE") // Belgium
	bg = countryCode("BG") // Bulgaria
	bh = countryCode("BH") // Bahrain
	br = countryCode("BR") // Brazil
	by = countryCode("BY") // Republic of Belarus
	ch = countryCode("CH") // Switzerland
	cr = countryCode("CR") // Costa Rica
	cy = countryCode("CY") // Cyprus
	cz = countryCode("CZ") // Czech Republic
	de = countryCode("DE") // Germany
	dk = countryCode("DK") // Denmark
	do = countryCode("DO") // Dominican Republic
	ee = countryCode("EE") // Estonia
	es = countryCode("ES") // Spain
	fi = countryCode("FI") // Finland
	fo = countryCode("FO") // Faroe Islands
	fr = countryCode("FR") // France
	gb = countryCode("GB") // United Kingdom
	ge = countryCode("GE") // Georgia
	gi = countryCode("GI") // Gibraltar
	gl = countryCode("GL") // Greenland
	gr = countryCode("GR") // Greece
	gt = countryCode("GT") // Guatemala
	hr = countryCode("HR") // Croatia
	hu = countryCode("HU") // Hungary
	ie = countryCode("IE") // Ireland
	il = countryCode("IL") // Israel
	iq = countryCode("IQ") // Iraq
	is = countryCode("IS") // Iceland
	it = countryCode("IT") // Italy
	jo = countryCode("JO") // Jordan
	kw = countryCode("KW") // Kuwait
	kz = countryCode("KZ") // Kazakhstan
	lb = countryCode("LB") // Lebanon
	lc = countryCode("LC") // Saint Lucia
	li = countryCode("LI") // Liechtenstein
	lt = countryCode("LT") // Lithuania
	lu = countryCode("LU") // Luxembourg
	lv = countryCode("LV") // Latvia
	mc = countryCode("MC") // Monaco
	md = countryCode("MD") // Moldova
	me = countryCode("ME") // Montenegro
	mk = countryCode("MK") // Macedonia
	mr = countryCode("MR") // Mauritania
	mt = countryCode("MT") // Malta
	mu = countryCode("MU") // Mauritius
	nl = countryCode("NL") // Netherlands
	no = countryCode("NO") // Norway
	pk = countryCode("PK") // Pakistan
	pl = countryCode("PL") // Poland
	ps = countryCode("PS") // Palestine
	pt = countryCode("PT") // Portugal
	qa = countryCode("QA") // Qatar
	ro = countryCode("RO") // Romania
	rs = countryCode("RS") // Serbia
	sa = countryCode("SA") // Saudi Arabia
	sc = countryCode("SC") // Seychelles
	se = countryCode("SE") // Sweden
	si = countryCode("SI") // Slovenia
	sk = countryCode("SK") // Slovakia
	sm = countryCode("SM") // San Marino
	st = countryCode("ST") // Sao Tome and Principe
	sv = countryCode("SV") // El Salvador
	tl = countryCode("TL") // Timor-Leste
	tn = countryCode("TN") // Tunisia
	tr = countryCode("TR") // Turkey
	ua = countryCode("UA") // Ukraine
	va = countryCode("VA") // Vatican City State
	vg = countryCode("VG") // Virgin Islands
	xk = countryCode("XK") // Kosovo

	gf = countryCode("GF") // French Guiana
	gp = countryCode("GP") // Guadaloupe
	mq = countryCode("MQ") // Martinique
	re = countryCode("RE") // Reunion
	pf = countryCode("PF") // French Polynesia
	tf = countryCode("TF") // French Southern Territories
	yt = countryCode("YT") // Mayotte
	nc = countryCode("NC") // New Caledonia
	bl = countryCode("BL") // Saint Barthélemy
	mf = countryCode("MF") // Collectivity of Saint Martin
	pm = countryCode("PM") // Saint Pierre and Miquelon
	wf = countryCode("WF") // Wallis and Futuna Islands
	im = countryCode("IM") // Isle of Man
	je = countryCode("JE") // Jersey
	gg = countryCode("GG") // Guernsey
	ax = countryCode("AX") // Åland Islands

	// Experimental IBAN Countries
	dz = countryCode("DZ") // Algeria
	ao = countryCode("AO") // Angola
	bj = countryCode("BJ") // Benin
	bf = countryCode("BF") // Burkina Faso
	bi = countryCode("BI") // Burundi
	cm = countryCode("CM") // Cameroon
	cv = countryCode("CV") // Cape Verde
	cf = countryCode("CF") // Central African Republic
	td = countryCode("TD") // Chad
	km = countryCode("KM") // Comoros
	cg = countryCode("CG") // Congo
	dj = countryCode("DJ") // Djibouti
	eg = countryCode("EG") // Egypt
	ga = countryCode("GA") // Gabon
	gw = countryCode("GW") // Guinea-Bissau
	hn = countryCode("HN") // Honduras
	ir = countryCode("IR") // Iran
	ci = countryCode("CI") // Ivory Coast
	mg = countryCode("MG") // Madagascar
	ml = countryCode("ML") // Mali
	ma = countryCode("MA") // Morocco
	mz = countryCode("MZ") // Mozambique
	ni = countryCode("NI") // Nicaragua
	ne = countryCode("NE") // Niger
	sn = countryCode("SN") // Senegal
	tg = countryCode("TG") // Togo
)
