package consts

import "github.com/vdlbk/mimir/models"

const (
	AD = models.CountryCode("AD") // Andorra
	AE = models.CountryCode("AE") // United Arab Emirates
	AL = models.CountryCode("AL") // Albania
	AT = models.CountryCode("AT") // Austria
	AZ = models.CountryCode("AZ") // Azerbaijan
	BA = models.CountryCode("BA") // BA – Bosnia and Herzegovina
	BE = models.CountryCode("BE") // Belgium
	BG = models.CountryCode("BG") // Bulgaria
	BH = models.CountryCode("BH") // Bahrain
	BR = models.CountryCode("BR") // Brazil
	BY = models.CountryCode("BY") // Republic of Belarus
	CH = models.CountryCode("CH") // Switzerland
	CR = models.CountryCode("CR") // Costa Rica
	CY = models.CountryCode("CY") // Cyprus
	CZ = models.CountryCode("CZ") // Czech Republic
	DE = models.CountryCode("DE") // Germany
	DK = models.CountryCode("DK") // Denmark
	DO = models.CountryCode("DO") // Dominican Republic
	EE = models.CountryCode("EE") // Estonia
	ES = models.CountryCode("ES") // Spain
	FI = models.CountryCode("FI") // Finland
	FO = models.CountryCode("FO") // Faroe Islands
	FR = models.CountryCode("FR") // France
	GB = models.CountryCode("GB") // United Kingdom
	GE = models.CountryCode("GE") // Georgia
	GI = models.CountryCode("GI") // Gibraltar
	GL = models.CountryCode("GL") // Greenland
	GR = models.CountryCode("GR") // Greece
	GT = models.CountryCode("GT") // Guatemala
	HR = models.CountryCode("HR") // Croatia
	HU = models.CountryCode("HU") // Hungary
	IE = models.CountryCode("IE") // Ireland
	IL = models.CountryCode("IL") // Israel
	IQ = models.CountryCode("IQ") // Iraq
	IS = models.CountryCode("IS") // Iceland
	IT = models.CountryCode("IT") // Italy
	JO = models.CountryCode("JO") // Jordan
	KW = models.CountryCode("KW") // Kuwait
	KZ = models.CountryCode("KZ") // Kazakhstan
	LB = models.CountryCode("LB") // Lebanon
	LC = models.CountryCode("LC") // Saint Lucia
	LI = models.CountryCode("LI") // Liechtenstein
	LT = models.CountryCode("LT") // Lithuania
	LU = models.CountryCode("LU") // Luxembourg
	LV = models.CountryCode("LV") // Latvia
	MC = models.CountryCode("MC") // Monaco
	MD = models.CountryCode("MD") // Moldova
	ME = models.CountryCode("ME") // Montenegro
	MK = models.CountryCode("MK") // Macedonia
	MR = models.CountryCode("MR") // Mauritania
	MT = models.CountryCode("MT") // Malta
	MU = models.CountryCode("MU") // Mauritius
	NL = models.CountryCode("NL") // Netherlands
	NO = models.CountryCode("NO") // Norway
	PK = models.CountryCode("PK") // Pakistan
	PL = models.CountryCode("PL") // Poland
	PS = models.CountryCode("PS") // Palestine
	PT = models.CountryCode("PT") // Portugal
	QA = models.CountryCode("QA") // Qatar
	RO = models.CountryCode("RO") // Romania
	RS = models.CountryCode("RS") // Serbia
	SA = models.CountryCode("SA") // Saudi Arabia
	SC = models.CountryCode("SC") // Seychelles
	SE = models.CountryCode("SE") // Sweden
	SI = models.CountryCode("SI") // Slovenia
	SK = models.CountryCode("SK") // Slovakia
	SM = models.CountryCode("SM") // San Marino
	ST = models.CountryCode("ST") // Sao Tome and Principe
	SV = models.CountryCode("SV") // El Salvador
	TL = models.CountryCode("TL") // Timor-Leste
	TN = models.CountryCode("TN") // Tunisia
	TR = models.CountryCode("TR") // Turkey
	UA = models.CountryCode("UA") // Ukraine
	VA = models.CountryCode("VA") // Vatican City State
	VG = models.CountryCode("VG") // Virgin Islands
	XK = models.CountryCode("XK") // Kosovo

	GF = models.CountryCode("GF") // French Guiana
	GP = models.CountryCode("GP") // Guadaloupe
	MQ = models.CountryCode("MQ") // Martinique
	RE = models.CountryCode("RE") // Reunion
	PF = models.CountryCode("PF") // French Polynesia
	TF = models.CountryCode("TF") // French Southern Territories
	YT = models.CountryCode("YT") // Mayotte
	NC = models.CountryCode("NC") // New Caledonia
	BL = models.CountryCode("BL") // Saint Barthélemy
	MF = models.CountryCode("MF") // Collectivity of Saint Martin
	PM = models.CountryCode("PM") // Saint Pierre and Miquelon
	WF = models.CountryCode("WF") // Wallis and Futuna Islands
	IM = models.CountryCode("IM") // Isle of Man
	JE = models.CountryCode("JE") // Jersey
	GG = models.CountryCode("GG") // Guernsey
	AX = models.CountryCode("AX") // Åland Islands
)
